---
$schemaver: '2.0'
repo_url: https://github.com/byu-oit/cas-saml-auth
software:
  - name: cas-saml-auth
    type: Background Process
    aliases:
    short_description: Plugin for SAML 2.0 authentication in CAS
    assignment_group: gro:AD-Identity and Access Management
    notes:
    maintained_by:
    developed_by_byu: true
    ddd:
        business_domain:
        ubiquitous_language_url:
        context_map_url:
    links:
        system_documentation_url: https://github.com/byu-oit/cas-saml-auth
        swagger_urls:
    microservice: false
    technologies_used:
      - Groovy
      - Java
    stages:
        production:
            urls:
                product_page: n
                physical_url:
                virtual_url:
            hosting_location: BYU
            aws_account:
            relationships:
                depends_on:
                    db_read_write:
                    db_read_only:
                    software:
                supports:
                    software:
                    service:
                reverse_proxy:
                runs_on:
                    server_cluster:
                    virtual_server:
                    rack_server:
                    blade_server:
    tags:
        data-sensitivity: confidential
        app: cas-saml-auth
        team: gro:AD-Identity and Access Management
